---
title: "RSVPLG02: Switch-Cost Analyses"
author: "David Fencsik"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(rstatix)
this_file = "08-Switching"
source_file = "02-FilterData"
dataFile = sprintf("%s.RData", source_file)
```

# Summary

The purpose of this analysis is to look at switch costs, starting with whether there is any evidence of switching between scopes.

# Load data files

```{r, loaddata1, include=FALSE}
if(!file.exists(dataFile)) {
  sprintf("Cannot find file %s", dataFile)
  knitr::knit_exit()
}
```

```{r, loaddata2}
load(dataFile)
```

# Overall Switching Effects

Plots and t-test of T2|T1 accuracy on switch and no switch trials

```{r switchplot, fig.height=4, fig.width=4}
x = rsvpAggregate |>
  mutate(switch = ifelse(t1_level == t2_level, "noswitch", "switch")) |>
  group_by(sub, switch) |>
  summarize(acc = mean(t2t1acc), .groups="drop")

diff = x |>
  pivot_wider(names_from=switch,
              values_from=acc) |>
  mutate(d = noswitch - switch)

x |>
  ggplot(aes(switch, acc)) +
  geom_violin(draw_quantiles=c(.25, .5, .75)) +
  geom_jitter(width=.15, height=0, color="black", shape="circle open") +
  stat_summary(fun=mean, geom="point", color="red", shape="cross", size=5) +
  theme_classic()

diff |>
  ggplot(aes(x="", y=d)) +
  geom_violin(draw_quantiles=c(.25, .5, .75)) +
  geom_hline(yintercept=0, linetype=2, color="gray") +
  geom_jitter(width=.15, height=0, color="black", shape="circle open") +
  stat_summary(fun=mean, geom="point", color="red", shape="cross", size=5) +
  theme_classic()

x |>
  group_by(switch) |>
  get_summary_stats(acc, type = "mean_sd")

diff |>
  shapiro_test(d)

ggqqplot(diff, "d")

x |>
  t_test(acc ~ switch, paired=TRUE)
```

```{r switchplotbylevel1, fig.height=4, fig.width=8}
x = rsvpAggregate |>
  mutate(switch = ifelse(t1_level == t2_level, "noswitch", "switch")) |>
  group_by(sub, switch, t2_level) |>
  summarize(acc = mean(t2t1acc), .groups="drop")

diff = x |>
  pivot_wider(names_from=switch,
              values_from=acc) |>
  mutate(d = noswitch - switch)

x |>
  ggplot(aes(switch, acc)) +
  geom_violin(draw_quantiles=c(.25, .5, .75)) +
  geom_jitter(width=.15, height=0, color="black", shape="circle open") +
  stat_summary(fun=mean, geom="point", color="red", shape="cross", size=5) +
  facet_wrap(~t2_level) +
  theme_classic()
```

```{r switchplotbylevel2, fig.height=4, fig.width=4}
diff |>
  ggplot(aes(x=t2_level, y=d)) +
  geom_violin(draw_quantiles=c(.25, .5, .75)) +
  geom_hline(yintercept=0, linetype=2, color="gray") +
  geom_jitter(width=.15, height=0, color="black", shape="circle open") +
  stat_summary(fun=mean, geom="point", color="red", shape="cross", size=5) +
  theme_classic()

x |>
  group_by(t2_level, switch) |>
  get_summary_stats(acc, type = "mean_sd")

diff |>
  group_by(t2_level) |>
  shapiro_test(d)
```

```{r switchplotbylevel3, fig.height=4, fig.width=8}
diff |>
  ggqqplot("d", facet.by="t2_level")

x |>
  anova_test(dv=acc,
             wid=sub,
             within=c(t2_level, switch))

x |>
  group_by(t2_level) |>
  t_test(acc ~ switch, paired=TRUE)
```
