---
title: "Analyze Data from Fall 2023 PSYC 491C"
author: "David Fencsik"
date: "`r Sys.Date()`"
output: html_document
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
library(tidyverse)
dataFile = "RSVPLG01-20239-491C.RData"
```

# Load data files

```{r, loaddata1}
if(!file.exists(dataFile)) {
  sprintf("Cannot find file %s", rsvpDataFile)
  knitr::knit_exit()
}
```

```{r, loaddata2}
load(dataFile)
dfRSVP = rsvp20239
dfSurvey = survey20239
```

# Clean data

```{r, cleanRSVPdata}
  dfRSVP = dfRSVP |>
    filter(blocktyp == "Experiment" & trial_type == "exp") |>
    filter(t1_acc >= 0 & t2_acc >= 0)
  dfSurvey$gender = factor(dfSurvey$gender)
  # create sum of PROMIS-A scores'
  dfSurvey = dfSurvey |>
    rowwise() |> mutate(sumpromisa=sum(c_across(starts_with("promisa"))))
  x = median(dfSurvey$sumpromisa)
  dfSurvey = dfSurvey |>
    rowwise() |> mutate(anxiety=if_else(sumpromisa <= x, "low", "high"))
  summary(dfRSVP)
  summary(dfSurvey)
```

Generate data summary and run ANOVA from Fall 2023 PSYC 491C

```{r, datasummary}
rsvp = dfRSVP |>
  filter(t1_acc == 1 & t2_lag > 0) |>
  group_by(sub, t1_level, t2_level, t2_lag) |>
  summarize(t2acc=mean(t2_acc, na.rm=TRUE)) |>
  ungroup()
rsvp$anxiety = ""
for (i in 1:nrow(dfSurvey)) {
  rsvp$anxiety[rsvp$sub == dfSurvey$sub[i]] = dfSurvey$anxiety[i]
}

library(rstatix)
rsvp |>
  anova_test(t2acc ~ t1_level*t2_level*t2_lag*anxiety +
             Error(sub/(t1_level*t2_level*t2_lag)), effect.size="pes")
```

Output data file for JASP

```{r, output4jasp}
rsvp = rsvp |>
  mutate(t1_level = ifelse(t1_level == "global", "G", "L")) |>
  mutate(t2_level = ifelse(t2_level == "global", "G", "L"))
rsvp$combo = with(rsvp, paste(t1_level, t2_level, t2_lag, sep=""))
rsvpw = rsvp |>
  pivot_wider(names_from=combo,
              values_from=t2acc,
              id_cols=c("sub", "anxiety"))
write.csv(rsvpw, "RSVPLG01-Experiment-20239-491C-JASP.csv",
          row.names=FALSE)
```
