---
title: "Prepare Data"
author: "David Fencsik"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set variables to select from RSVP data file
variables = c(
  'exp',
  'ver',
  'mod.utc',
  'sub',
  'experimenter',
  'datetime',
  'blocktyp',
  'sess',
  'trial',
  'trial_type',
  'trial_time',
  't1_level',
  't2_level',
  't2_lag',
  'global_letters',
  'local_letters',
  't1_pos',
  't1',
  't1_corr',
  't1_resp',
  't1_acc',
  't2',
  't2_corr',
  't2_resp',
  't2_acc',
  't1_rt',
  't2_rt'
)
```

# Load Data Files

## Combine Individual RSVP Data Files

Gathers all the data files together, selecting a common set of headings

```{r loadrsvp}
testmode = TRUE
if (testmode) {
  dataDir = "/Users/fencsik/PsychoPy/RSVPLG/rsvplg01/data"
} else {
  dataDir = rstudioapi::selectDirectory(caption="Select RSVP Data Files Directory",
                                        label="Select",
                                        path=getwd())
}
source("gatherdata.r")
rsvpData = GatherData(datadir, variables)
summary(rsvpData)
```

## Load Survey Data

Load the survey CSV file

```{r loadsurvey}
if (testmode) {
  surveyFile = "/Users/fencsik/PsychoPy/RSVPLG/rsvplg01/SurveyData2023-11-25.csv"
} else {
  surveyFile = rstudioapi::selectFile(caption="Select Survey Data File",
                                      label="Select",
                                      path=getwd(),
                                      filter="CSV Files (*.csv)",
                                      existing=TRUE)
}

if(!is.null(surveyFile)) {
  surveyData = read.csv(surveyFile)
  summary(surveyData)
}
```

# Clean Data

1. Remove incomplete data due to crashes

2. Correct subject ID typos

3. Removes minors


```{r cleandata}
# remove data lines from a crash
#dt = dt[!is.na(dt$sub), ]

# remove subjects w/ ID >= 900 (these were test runs)

# correct subject ID typos
#dt$sub[dt$sub == 317 & dt$experimenter == "SN"] = 137
#dt$sub[dt$sub == 514 & dt$experimenter == "AGM"] = 154
#dt$sub[dt$sub == 157 & dt$experimenter == "ng"] = 156

# remove known minors
minors = c(106, 125, 126, 136, 145, 150, 214, 217, 218)

#with(dt, tapply(trial, list(sub, blocktyp), length))
```

# Randomize IDs

Generate randomly mapped subjet IDs and removes exp ID and run time for full anonymity
